version: "3"

services:

  elasticsearch:
    image: elasticsearch:7.2.0
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node


  kibana:
    image: kibana:7.2.0
    ports:
      - 5601:5601
