# .eslintrc.yml
# version 2017/09/30
# by NaruseJun (@N4RU5E)

parserOptions:
  ecmaVersion: 2017

env:
  node: true
  browser: true
  commonjs: true

rules:
  
  # Possible Errors
  for-direction:
    - error
  getter-return:
    - error
  no-await-in-loop:
    - warn
  no-compare-neg-zero:
    - error
  no-cond-assign:
    - warn
  no-console:
    - warn
  no-constant-condition:
    - error
  no-control-regex:
    - warn
  no-debugger:
    - error
  no-dupe-args:
    - error
  no-dupe-keys:
    - error
  no-duplicate-case:
    - error
  no-empty:
    - error
  no-empty-character-class:
    - error
  no-ex-assign:
    - error
  no-extra-boolean-cast:
    - error
  no-extra-parens:
    - warn
  no-extra-semi:
    - error
  no-func-assign:
    - error
  no-inner-declarations:
    - error
  no-invalid-regexp:
    - error
  no-irregular-whitespace:
    - error
  no-obj-calls:
    - error
  no-prototype-builtins:
    - error
  no-regex-spaces:
    - error
  no-sparse-arrays:
    - error
  no-template-curly-in-string:
    - error
  no-unexpected-multiline:
    - error
  no-unreachable:
    - error
  no-unsafe-finally:
    - error
  no-unsafe-negation:
    - error
  use-isnan:
    - error
  valid-jsdoc:
    - off
  valid-typeof:
    - error

  # Best Practices
  accessor-pairs:
    - off
  array-callback-return:
    - error
  block-scoped-var:
    - error
  class-methods-use-this:
    - warn
  complexity:
    - off
  consistent-return:
    - error
  curly:
    - error
  default-case:
    - error
  dot-location:
    - error
    - property
  dot-notation:
    - error
  eqeqeq:
    - error
    - smart
  guard-for-in:
    - error
  no-alert:
    - warn
  no-caller:
    - error
  no-case-declarations:
    - error
  no-div-regex:
    - error
  no-else-return:
    - error
  no-empty-function:
    - error
  no-empty-pattern:
    - error
  no-eq-null:
    - error
  no-eval:
    - error
  no-extend-native:
    - error
  no-extra-bind:
    - error
  no-extra-label:
    - error
  no-fallthrough:
    - warn
  no-floating-decimal:
    - error
  no-global-assign:
    - error
  no-implicit-coercion:
    - error
  no-implicit-globals:
    - error
  no-implied-eval:
    - error
  no-invalid-this:
    - error
  no-iterator:
    - error
  no-labels:
    - error
    - allowLoop: true
  no-lone-blocks:
    - error
  no-loop-func:
    - error
  no-magic-numbers:
    - off
  no-multi-spaces:
    - error
  no-multi-str:
    - error
  no-new:
    - error
  no-new-func:
    - error
  no-new-wrappers:
    - error
  no-octal:
    - error
  no-octal-escape:
    - error
  no-param-reassign:
    - warn
  no-proto:
    - error
  no-redeclare:
    - error
  no-restricted-properties:
    - off
  no-return-assign:
    - error
  no-return-await:
    - error
  no-script-url:
    - warn
  no-self-assign:
    - error
  no-self-compare:
    - error
  no-sequences:
    - error
  no-throw-literal:
    - error
  no-unmodified-loop-condition:
    - error
  no-unused-expressions:
    - error
  no-unused-labels:
    - error
  no-useless-call:
    - error
  no-useless-concat:
    - error
  no-useless-escape:
    - error
  no-useless-return:
    - error
  no-void:
    - error
  no-warning-comments:
    - warn
  no-with:
    - error
  prefer-promise-reject-errors:
    - error
    - allowEmptyReject: true
  radix:
    - off
  require-await:
    - error
  vars-on-top:
    - off
  wrap-iife:
    - error
    - inside
  yoda:
    - error
    - never
    - exceptRange: true

  # Strict Mode
  strict:
    - error
    - global

  # Variables
  init-declarations:
    - off
  no-catch-shadow:
    - off
  no-delete-var:
    - error
  no-label-var:
    - error
  no-restricted-globals:
    - off
  no-shadow:
    - error
    - builtinGlobals: true
      hoist: all
  no-shadow-restricted-names:
    - error
  no-undef:
    - error
  no-undef-init:
    - error
  no-undefined:
    - error
  no-unused-vars:
    - error
    - argsIgnorePattern: _
  no-use-before-define:
    - error

  # Node.js and CommonJS
  callback-return:
    - error
  global-require:
    - error
  handle-callback-err:
    - error
  no-buffer-constructor:
    - error
  no-mixed-requires:
    - error
  no-new-require:
    - error
  no-path-concat:
    - error
  no-process-env:
    - off
  no-process-exit:
    - warn
  no-restricted-modules:
    - off
  no-sync:
    - warn

  # Stylistic Issues
  array-bracket-newline:
    - error
    - multiline: true
  array-bracket-spacing:
    - error
    - never
  array-element-newline:
    - error
    - multiline: true
  block-spacing:
    - error
    - always
  brace-style:
    - error
    - stroustrup
  camelcase:
    - error
  capitalized-comments:
    - off
  comma-dangle:
    - error
    - always-multiline
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  consistent-this:
    - off
  eol-last:
    - error
    - always
  func-call-spacing:
    - error
    - never
  func-name-matching:
    - error
    - includeCommonJSModuleExports: true
  func-names:
    - error
    - never
  func-style:
    - error
    - expression
  function-paren-newline:
    - error
    - never
  id-blacklist:
    - off
  id-length:
    - off
  id-match:
    - off
  indent:
    - error
    - tab
    - SwitchCase: 1
      outerIIFEBody: 0
      MemberExpression: 0
  jsx-quotes:
    - error
    - prefer-double
  key-spacing:
    - error
    - mode: strict 
      beforeColon: false
      afterColon: true
  keyword-spacing:
    - error
    - before: false
      after: false
  line-comment-position:
    - error
    - position: above
  linebreak-style:
    - error
    - unix
  lines-around-comment:
    - off
  max-depth:
    - off
  max-len:
    - off
  max-lines:
    - off
  max-nested-callbacks:
    - off
  max-params:
    - off
  max-statements:
    - off
  max-statements-per-line:
    - error
    - max: 1
  multiline-ternary:
    - error
    - never
  new-cap:
    - error
    - newIsCap: true
      capIsNew: true
      properties: true
  new-parens:
    - error
  newline-per-chained-call:
    - off
  no-array-constructor:
    - error
  no-bitwise:
    - warn
  no-continue:
    - off
  no-inline-comments:
    - error
  no-lonely-if:
    - error
  no-mixed-operators:
    - error
    - groups:
      - ["&&", "||"]
  no-mixed-spaces-and-tabs:
    - error
  no-multi-assign:
    - error
  no-multiple-empty-lines:
    - error
    - max: 1
  no-negated-condition:
    - off
  no-nested-ternary:
    - error
  no-new-object:
    - error
  no-plusplus:
    - off
  no-restricted-syntax:
    - off
  no-tabs:
    - off
  no-ternary:
    - off
  no-trailing-spaces:
    - error
  no-underscore-dangle:
    - off
  no-unneeded-ternary:
    - error
  no-whitespace-before-property:
    - error
  nonblock-statement-body-position:
    - error
    - beside
  object-curly-newline:
    - error
    - multiline: true
  object-curly-spacing:
    - error
    - never
  object-property-newline:
    - error
    - allowMultiplePropertiesPerLine: true
  one-var:
    - error
    - never
  one-var-declaration-per-line:
    - error
    - always
  operator-assignment:
    - error
    - always
  operator-linebreak:
    - error
    - none
  padded-blocks:
    - error
    - never
  padding-line-between-statements:
    - off
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - double
    - avoidEscape: true
  require-jsdoc:
    - off
  semi:
    - error
    - always
  semi-spacing:
    - error
    - before: false
      after: true
  semi-style:
    - error
    - last
  sort-keys:
    - off
  sort-vars:
    - off
  space-before-blocks:
    - error
    - never
  space-before-function-paren:
    - error
    - never
  space-in-parens:
    - error
    - never
  space-infix-ops:
    - error
  space-unary-ops:
    - error
  spaced-comment:
    - error
    - always
  switch-colon-spacing:
    - error
    - before: false
      after: true
  template-tag-spacing:
    - error
    - always
  unicode-bom:
    - error
    - never
  wrap-regex:
    - off

  # ECMAScript 6
  arrow-body-style:
    - error
    - as-needed
  arrow-parens:
    - error
    - as-needed
  arrow-spacing:
    - error
    - before: true
      after: true
  constructor-super:
    - error
  generator-star-spacing:
    - error
    - named:
        before: false
        after: true
      anonymous:
        before: false
        after: false
      method:
        before: true
        after: false
  no-class-assign:
    - error
  no-confusing-arrow:
    - error
    - allowParens: true
  no-const-assign:
    - error
  no-dupe-class-members:
    - error
  no-duplicate-imports:
    - error
  no-new-symbol:
    - error
  no-restricted-imports:
    - off
  no-this-before-super:
    - error
  no-useless-computed-key:
    - error
  no-useless-constructor:
    - error
  no-useless-rename:
    - error
  no-var:
    - error
  object-shorthand:
    - error
    - always
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  prefer-destructuring:
    - error
    - array: true
      object: true
    - enforceForRenamedProperties: true
  prefer-numeric-literals:
    - error
  prefer-rest-params:
    - error
  prefer-spread:
    - error
  prefer-template:
    - error
  require-yield:
    - error
  rest-spread-spacing:
    - error
    - never
  sort-imports:
    - off
  symbol-description:
    - error
  template-curly-spacing:
    - error
    - never
  yield-star-spacing:
    - error
    - before: false
      after: true
