- hosts: localhost
  connection: local

  tasks:

    - name: create directory
      tags:
        - file
      file:
        state: directory
        path: ~/{{ item }}
        mode: 0700
      loop:
        - .ssh
        - .gnupg
        - .config/fish

    - name: link files
      tags:
        - file
      file:
        state: link
        src: "{{ playbook_dir }}/files/{{ item.src }}"
        path: ~/{{ item.dest }}
      loop:
        - src: eslintrc.yml
          dest: .eslintrc.yml
        - src: database
          dest: .database
        - src: devcontainer
          dest: .devcontainer
        - src: gitconfig
          dest: .gitconfig
        - src: gitignore_global
          dest: .gitignore_global
        - src: profile.sh
          dest: .zprofile
        - src: ssh.config
          dest: .ssh/config
        - src: ssh.control
          dest: .gnupg/sshcontrol
        - src: gpg-agent.conf
          dest: .gnupg/gpg-agent.conf
        - src: config.fish
          dest: .config/fish/config.fish
        - src: functions
          dest: .config/fish/functions
        - src: completions
          dest: .config/fish/completions
        - src: tmux.conf
          dest: .tmux.conf

    - name: install brew packages
      tags:
        - brew
      homebrew:
        update_homebrew: yes
        upgrade_all: yes
        name:
          - beeftornado/rmtree/brew-rmtree
          - ffmpeg
          - fish
          - git
          - git-lfs
          - gnupg
          - go
          - graphviz
          - imagemagick
          - jq
          - make
          - mtr
          - nodejs
          - python3
          - ruby
          - terraform
          - tmux
          - wget
          - yarn
          - youtube-dl

    - name: install brew cask packages
      tags:
        - cask
      homebrew_cask:
        greedy: yes
        accept_external_apps: yes
        name:
          - 1password
          - docker
          - firefox
          - fork
          - google-chrome
          - google-cloud-sdk
          - google-japanese-ime
          - java
          - karabiner-elements
          - onedrive
          - the-unarchiver
          - thunderbird
          - visual-studio-code
          - wireshark

    - name: install pip packages
      tags:
        - pip
      pip:
        virtualenv: ~/.venv
        name:
          - ansible
          - awscli
          - aws-sam-cli
          - online-judge-tools
          - yq

    - name: install npm packages
      tags:
        - npm
      npm:
        global: yes
        name: "{{ item }}"
      loop:
        - eslint
