- hosts: localhost
  connection: local

  tasks:

    - name: create directory
      tags:
        - file
      file:
        state: directory
        path: ~/{{ item }}
        mode: 0700
      loop:
        - .ssh
        - .gnupg
        - .npm/lib
        - .config/karabiner
        - .config/fish
        - .local/share/fish

    - name: link files
      tags:
        - file
      file:
        state: link
        src: "{{ playbook_dir }}/files/{{ item.src }}"
        path: ~/{{ item.dest }}
      loop:
        - src: profile.sh
          dest: .zprofile
        - src: prettierrc.yml
          dest: .prettierrc.yml
        - src: eslintrc.yml
          dest: .eslintrc.yml
        - src: npmrc
          dest: .npmrc
        - src: tmux.conf
          dest: .tmux.conf
        - src: gitconfig
          dest: .gitconfig
        - src: gitignore_global
          dest: .gitignore_global
        - src: ssh.config
          dest: .ssh/config
        - src: ssh.control
          dest: .gnupg/sshcontrol
        - src: gpg-agent.conf
          dest: .gnupg/gpg-agent.conf
        - src: config.fish
          dest: .config/fish/config.fish
        - src: functions
          dest: .config/fish/functions
        - src: completions
          dest: .config/fish/completions
        - src: database
          dest: .database
        - src: devcontainer
          dest: .devcontainer

    - name: link files on Google Drive
      tags:
        - file
      file:
        state: link
        src: ~/GoogleDrive/{{ item.src }}
        path: ~/{{ item.dest }}
      loop:
        - src: app/fish_history
          dest: .local/share/fish/fish_history
        - src: app/karabiner.json
          dest: .config/karabiner/karabiner.json

    - name: update homebrew itself
      tags:
        - brew
        - cask
      homebrew:
        update_homebrew: yes

    - name: install brew packages
      tags:
        - brew
      homebrew:
        state: latest
        name:
          - beeftornado/rmtree/brew-rmtree
          - fish
          - git
          - git-lfs
          - gnupg
          - go
          - graphviz
          - imagemagick
          - jq
          - make
          - mas
          - mtr
          - node
          - protobuf
          - python
          - ruby
          - rustup
          - terraform
          - tmux
          - wget

    - name: install brew cask packages
      tags:
        - cask
      homebrew_cask:
        state: latest
        name:
          - 1password
          - adoptopenjdk
          - docker
          - firefox
          - fork
          - google-backup-and-sync
          - google-chrome
          - google-cloud-sdk
          - google-japanese-ime
          - karabiner-elements
          - the-unarchiver
          - thunderbird
          - visual-studio-code
          - wireshark
          - zoomus

    - name: install mas packages
      tags:
        - mas
      mas:
        name: "{{ item }}"
      loop:
        - Magnet
        - Microsoft Remote Desktop

    - name: install pip packages
      tags:
        - pip
      pip:
        state: latest
        virtualenv: ~/.venv
        name:
          - ansible
          - awscli
          - online-judge-tools
          - pip
          - yq

    - name: install npm packages
      tags:
        - npm
      npm:
        state: latest
        global: yes
        name: "{{ item }}"
      loop:
        - eslint
        - firebase-tools
        - ts-node
        - typescript

    - name: install go packages
      tags:
        - go
      go_get:
        name: "{{ item }}"
      loop:
        - github.com/ramya-rao-a/go-outline
        - golang.org/x/tools/gopls
        - google.golang.org/grpc/cmd/protoc-gen-go-grpc
        - google.golang.org/protobuf/cmd/protoc-gen-go
