- hosts: localhost
  connection: local

  tasks:
    - import_tasks: file.yml
      vars:
        homebrew_prefix:
          x86_64: /usr/local
          arm64: /opt/homebrew
      tags:
        - file

    - import_tasks: link.yml
      tags:
        - link

    - name: update homebrew itself
      tags:
        - brew
        - cask
      homebrew:
        update_homebrew: yes

    - name: install brew packages
      tags:
        - brew
      homebrew:
        state: latest
        name:
          - beeftornado/rmtree/brew-rmtree
          - fish
          - git
          - git-lfs
          - gnupg
          - go
          - graphviz
          - imagemagick
          - jq
          - make
          - mas
          - mtr
          - node
          - protobuf
          - protoc-gen-grpc-web
          - python
          - ruby
          - rustup
          - terraform
          - wget

    - name: install brew cask packages
      tags:
        - cask
      homebrew_cask:
        state: latest
        name:
          - 1password
          - docker
          - firefox
          - fork
          - google-backup-and-sync
          - google-chrome
          - google-cloud-sdk
          - google-japanese-ime
          - karabiner-elements
          - openvpn-connect
          - visual-studio-code
          - wireshark

    - name: install mas packages
      tags:
        - mas
      mas:
        state: latest
        name: "{{ item }}"
      loop:
        - Magnet
        - Microsoft Remote Desktop

    - name: install pip packages
      tags:
        - pip
      pip:
        state: latest
        virtualenv: ~/.venv
        name:
          - ansible
          - awscli
          - online-judge-tools
          - pip
          - yq

    - name: install npm packages
      tags:
        - npm
      npm:
        state: latest
        global: yes
        name: "{{ item }}"
      loop:
        - "@cloudflare/wrangler"
        - "@protobuf-ts/plugin"
        - "@trivago/prettier-plugin-sort-imports"
        - npm-check-updates
        - prettier
        - ts-node

    - name: install go packages
      tags:
        - go
      go_get:
        name: "{{ item }}"
      loop:
        - google.golang.org/grpc/cmd/protoc-gen-go-grpc
        - google.golang.org/protobuf/cmd/protoc-gen-go
