- hosts: localhost
  connection: local

  tasks:
    - import_tasks: file.yml
      vars:
        homebrew_prefix:
          x86_64: /usr/local
          arm64: /opt/homebrew
      tags:
        - file

    - import_tasks: link.yml
      tags:
        - link

    - import_tasks: brew.yml

    - import_tasks: mas.yml
      tags:
        - mas

    - import_tasks: pip.yml
      tags:
        - pip

    - import_tasks: npm.yml
      tags:
        - npm

    - import_tasks: go.yml
      tags:
        - go
