- hosts: localhost
  connection: local

  tasks:
    - name: link files
      file:
        state: link
        src: "{{ playbook_dir }}/files/{{ item.src }}"
        path: ~/{{ item.dest }}
      loop:
        - src: eslintrc.yml
          dest: .eslintrc.yml
        - src: database
          dest: .database
        - src: devcontainer
          dest: .devcontainer
        - src: gitconfig
          dest: .gitconfig
        - src: gitignore_global
          dest: .gitignore_global
        - src: profile.bash
          dest: .bash_profile
        - src: profile.d
          dest: .profile.d
        - src: tmux.conf
          dest: .tmux.conf

    - name: install brew packages
      homebrew:
        name: "{{ item }}"
      loop:
        - bash-completion
        - beeftornado/rmtree/brew-rmtree
        - ffmpeg
        - git
        - git-lfs
        - gnupg
        - go
        - graphviz
        - imagemagick
        - jq
        - make
        - mtr
        - nodejs
        - python3
        - ruby
        - tmux
        - wget
        - yarn

    - name: install pip packages
      pip:
        name: "{{ item }}"
        virtualenv: ~/.venv
      loop:
        - ansible<2.8.0
        - awscli
        - aws-sam-cli
        - online-judge-tools

    - name: install brew cask packages
      homebrew_cask:
        name: "{{ item }}"
      loop:
        - 1password
        - firefox
        - fork
        - google-chrome
        - google-cloud-sdk
        - google-japanese-ime
        - karabiner-elements
        - onedrive
        - the-unarchiver
        - thunderbird
        - visual-studio-code
