mariadb:
  image: mariadb
  volumes:
    - "./mariadb:/var/lib/mysql"
  ports:
     - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=password

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  volumes:
     - "./phpmyadmin:/sessions"
  ports:
     - 8080:80
  environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mariadb
    - PMA_USER=root
    - PMA_PASSWORD=password
  links:
    - mariadb
