volumes:
  elasticsearch:

services:
  elasticsearch:
    image: elasticsearch:8.6.0
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms512m -Xms512m
  kibana:
    image: kibana:8.6.0
    ports:
      - 50301:5601
