version: "3"

volumes:
  elasticsearch:

services:
  elasticsearch:
    image: elasticsearch:7.9.3
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: -Xms512m -Xms512m
  kibana:
    image: kibana:7.9.3
    ports:
      - 18003:5601
