version: "3"

volumes:
  redis:
  redisinsight:

services:
  redis:
    image: redis
    volumes:
      - redis:/data
    ports:
      - 6379:6379
  redisinsight:
    image: redislabs/redisinsight
    volumes:
      - redisinsight:/db
    ports:
      - 18002:8001
